### ISSUE TITLE
board-id in burndown is ignored

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#100]
When running `trollolo burndown --new_sprint --board-id=78454 --output=trollolo` the `board-id` parameter is ignored and it uses the `board-id` of the previous sprint, which is in the last `burndown-data.yml` file.

**Comment by alexandergraul** [comment]
I'll work on this.

**Comment by alexandergraul** [comment]
for clarification: isn't this a new feature?
right now there is no `--board-id` for `trollolo burndown`.

**Comment by Ana06** [comment]
I think it appeared, at least some weeks ago, when running `trollolo --help`. Anyway, it is not important, if it is not implemented at all, we could implement it, it is already in other commands. :wink:

**Comment by Ana06** [comment]
@alexandergraul how are you going with this? :thinking:

**Comment by alexandergraul** [comment]
@Ana06 I will work on this in the upcoming days, I assume I will have a PR ready in the first half of the next week.
