### ISSUE TITLE
`trollolo show_backup` always shows archived cards

### ISSUE THREAD

**Issue by cornelius** [openSUSE/trollolo#13]
The `show_backup` command should not show archived cards by default. Maybe a switch `--show-archived` would be nice, which would show the card with an indication that it is an archived card.

**Comment by jimmykarily** [comment]
I think [this](https://github.com/openSUSE/trollolo/commit/e11b8a5f1192e66f26adacdc62d0e388bb856100) commit deprecated this issue. ```backup``` command no longer fetches archived cards so they are no longer shown with the ```show_backup``` command.

**Comment by cornelius** [comment]
Right. Closing this issue. Thanks for pointing this out.
