### ISSUE TITLE
Being able to generate burndown chart image

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#130]
Currently we have an option to select the working directory, where the data file is. At the moment the `png` with the burndown chart is in the same directory. We should implement a new option in `burndown` command, so that this directory can be different.

**Comment by rishabhptr** [comment]
@Ana06 If this is available, can I work on it?

**Comment by Ana06** [comment]
@rishabhptr sorry that I didn't answered before, I had skipped your comment. 🙈 

Sure! you can work on this! 😉
