### ISSUE TITLE
Solve Style/RegexpLiteral offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#133]
There is at least one offenses for Style/RegexpLiteral Rubocop cop, as you can see in [.rubocop_todo.yml](https://github.com/openSUSE/trollolo/blob/master/.rubocop_todo.yml).

Solve the offense. This cop support autocorrection, but the offense can not be automatically corrected.

**Comment by namangupta01** [comment]
can i work on it?

**Comment by Ana06** [comment]
@namangupta01 sure you can! actually you have already started 🤣
