### ISSUE TITLE
Solve Bundler/OrderedGems RuboCop cop offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#149]
Solve `Bundler/OrderedGems` RuboCop cop offenses. This cop checks that gems are alphabetically sorted within groups. More info: https://rubocop.readthedocs.io/en/latest/cops_bundler/#bundlerorderedgems 

**Tip:** The cop supports autocorrection.

**Comment by Atul9** [comment]
I am working on this issue
