### ISSUE TITLE
Solve Layout/DotPosition RuboCop cop offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#150]
Solve `Layout/DotPosition` RuboCop cop offenses, currently excluded in the [*rubocop_todo* file](https://github.com/openSUSE/trollolo/blob/master/.rubocop_todo.yml). This cop checks the . position in multi-line method calls. More info: https://rubocop.readthedocs.io/en/latest/cops_layout

**Tip:** The cop supports autocorrection.

**Comment by Atul9** [comment]
I am working on this issue
