### ISSUE TITLE
Solve Style/MixinUsage RuboCop cop offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#151]
Solve `Style/MixinUsage` RuboCop cop offenses, currently excluded in the [*rubocop_todo* file](https://github.com/openSUSE/trollolo/blob/master/.rubocop_todo.yml). This cop checks that `include`, `extend` and `prepend` statements appear inside classes and modules, not at the top level, so as to not affect the behavior of `Object`. More info: https://rubocop.readthedocs.io/en/latest/cops_style/#stylemixinusage

**Comment by Ronaq13** [comment]
Can I work on this?
