### ISSUE TITLE
Solve Performance/HashEachMethods RuboCop cop offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#152]
Solve `Performance/HashEachMethods` RuboCop cop offenses, currently excluded in the [*rubocop_todo* file](https://github.com/openSUSE/trollolo/blob/master/.rubocop_todo.yml). This cop checks for uses of `each_key` and `each_value` Hash methods. More info: https://rubocop.readthedocs.io/en/latest/cops_performance#performancehasheachmethods

**Tip:** The cop supports autocorrection.

**Comment by namangupta01** [comment]
@Ana06 Can i work on it?

**Comment by Ana06** [comment]
@namangupta01 there is already a PR for this, please take another issue 😉
