### ISSUE TITLE
invalid id error while using burndown command

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/trollolo#166]
Trollolo burndown generating this error
ERROR -- : [400 GET https://api.trello.com/1/boards/MYBOARDID?lists=open&cards=open&card_checklists=all]: invalid id

but my id is valid as  "trollolo get-cards --board-id=MyTrelloBoard" is working.

**Comment by rahul2240** [comment]
These test are also failing
create_burndown.py
  creates burndown chart with varying number of total story points and tasks (FAILED - 1)
  creates burndown chart with done tasks at the beginning (FAILED - 2)
  creates burndown chart of unfinished sprint (FAILED - 3)
  creates burndown chart with fast lane and no tasks (FAILED - 4)
  creates perfect burndown chart (FAILED - 5)
  creates burndown chart with unplanned cards (FAILED - 6)
  creates burndown chart with unplanned tasks on day one (FAILED - 7)

**Comment by namangupta01** [comment]
Hey @rahul2240 You are using MyTrelloBoard as the alias name to your `board-id` so you must have to provide id for the alias name MyTrelloBoard in .trollolorc. I think this would resolve your error. 🙂

**Comment by rahul2240** [comment]
@namangupta01 Thanks but as i mentioned my second command( "trollolo get-cards --board-id=MyTrelloBoard" ) is working. I have already provided id for the alias name in .trollolorc

**Comment by namangupta01** [comment]
Where have you put your id? In current working directory? Put it into the current user directory.

**Comment by namangupta01** [comment]
Yes, you are right i also got the error.

**Comment by rahul2240** [comment]
@namangupta01 😄 My tests are passing now. My tests were failing because docker was not installed in my system, If you are getting the same errors then I think installing docker will solve the problem 😄

**Comment by namangupta01** [comment]
The error i was getting because in burndown i was using alias name `MYBOARDID`  and in get-cards i was using `MyTrelloBoard` and i only configured `MyTrelloBoard` in my . trollolorc file.

**Comment by rahul2240** [comment]
As the issue is resolved so closing the issue 😄 .

**Comment by Ana06** [comment]
@rahul2240, @namangupta01 if you think that some documentation will help other people who face the same problem, a PR is really welcome :wink:

**Comment by namangupta01** [comment]
sure @Ana06 I will make a PR regarding this

**Comment by Ana06** [comment]
ok :+1:
