### ISSUE TITLE
rubocop Style/FrozenStringLiteralComment offence

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/trollolo#169]
Rubocop is failing because of "Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true"

**Comment by Ana06** [comment]
where? the last build in Travis is green: https://travis-ci.org/openSUSE/trollolo/builds/342254099?utm_source=github_status&utm_medium=notification

**Comment by Ana06** [comment]
how are you running rubocop? there should be something different between travis and your local setup 🤔

**Comment by rahul2240** [comment]
![sss](https://user-images.githubusercontent.com/25618739/36438458-ff9ee712-168f-11e8-8829-dc2ccc39977c.png)
@Ana06 I am using the same command as mentioned

**Comment by Ana06** [comment]
@rahul2240 

What Ruby version are you using? `ruby --version`

can you also check that the rubocop version is the correct one? `bundle exec "rubocop -V"`

**Comment by rahul2240** [comment]
I am using ruby 2.4.0p0 
also my rubocop version is 0.52.1
