### ISSUE TITLE
burndown-data-#{sprint.number}.yaml should be .yml

### ISSUE THREAD

**Issue by mdeniz** [openSUSE/trollolo#173]
As the standard extension for YAML files is `.yml` we should change this accordingly.

**Comment by Ronaq13** [comment]
I want to take it.

**Comment by Ronaq13** [comment]
#179

**Comment by Ronaq13** [comment]
Please review: #179

**Comment by cornelius** [comment]
The [YAML FAQ](http://yaml.org/faq.html) says to use `.yaml`. `.yml` is fine as well as it's used quite often. In the end I think it doesn't matter and I would not spend any effort on this.

**Comment by Ana06** [comment]
@cornelius 

> The YAML FAQ says to use .yaml. .yml is fine as well as it's used quite often. In the end I think it doesn't matter and I would not spend any effort on this.

ok :+1:
