### ISSUE TITLE
Missing check for true in unit test.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/trollolo#178]
I think there should be `.to be true` in lines 20 & 21 expect statements because now the test would pass in any scenario. :smile: 

https://github.com/openSUSE/trollolo/blob/d928c9417943ba2e8645cf08b2b30c7b1ebdd34e/spec/unit/cli_spec.rb#L14-L22

**Comment by Ana06** [comment]
If a test is wrong, you can directly open a PR to fix it, you don't need to open an issue. If it is wrong it has to be be fixed and there is no discussion, so we don't need an issue. :wink:

**Comment by Ronaq13** [comment]
I am working on this.
