### ISSUE TITLE
Getting DoneColumnNotFoundError

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/trollolo#189]
I am following https://github.com/openSUSE/trollolo/blob/master/man/trollolo.1.md and have also setup `.trollolorc` file. 
My `.trollolorc` file looks like this :

![screen shot 2018-03-06 at 3 32 19 am](https://user-images.githubusercontent.com/20709985/37002263-1196aef0-20ef-11e8-8981-19f97ad05ef1.png)

And my board looks like :
![screen shot 2018-03-06 at 4 09 25 am](https://user-images.githubusercontent.com/20709985/37003800-4b9244de-20f4-11e8-80b7-ee6b237d928d.png)

But when i run `trollolo burndown` i am getting the following error:
![screen shot 2018-03-06 at 9 10 37 pm](https://user-images.githubusercontent.com/20709985/37041707-d6e98108-2182-11e8-97b5-2df487c0f973.png)

**Comment by Ana06** [comment]
why is `done_column_name_regex` a list? I guess it should something like:

`done_column_name_regex: /\ADone/`

**Comment by namangupta01** [comment]
So Soory, i mistakenly added the wrong error screenshot. I have updated it now please have a look.

**Comment by namangupta01** [comment]
I found what is causing problem the problem is that `@settings.done_column_name_regex` is an array of string and what we actually need is the regular expression on the right hand side. I will create a pr regarding this.

**Comment by namangupta01** [comment]
I think it would be easy to use if we use `done_column` similarly we are using `not_done_columns` because we can easily convert the array of string into regex expression easily.

**Comment by Ana06** [comment]
As said in the PR, the code is fine, you just need to configure it correctly :wink: Closing....
