### ISSUE TITLE
newer codeclimate (codeclimate-test-reporter) version breaks test suite

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/trollolo#54]
Version 1.0 of codeclimate test reporter introduced changes that
break configurations for older versions and thus requires some
adaptations.

https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md#upgrading-from-pre-10-versions

**Comment by jimmykarily** [comment]
This breaks Travis builds so it is important that we apply a fix. With the changes introduced in codeclimate-test-reporter gem being breaking for older setups I see the following 3 options:

- Use the "new" config as described in the gem's README. This configuration does not break the builds when older version of the gem is being used. I cannot verify that the gem works but at we can solve the problem if it arises.
- Use the new config and also force the newer version in the Gemfile.
- Use the old config and force the old version in the Gemfile.

I suggest that we go with the second (force newer version and use the new configuration). Trollolo is a standalone application. I don't think setting  the minimum version will create any version conflicts for anybody. After all this is a dependency only for tests.

**Comment by manno** [comment]
I believe this has been fixed with #52 and can be closed?
