### ISSUE TITLE
Write back burndown chart graphics to Trello board

### ISSUE THREAD

**Issue by cornelius** [openSUSE/trollolo#64]
When generating the burndown chart graphics with `trollolo burndown --plot` or `trollolo plot` there should be a new option `--upload` which uploads the generated png file to the card showing the burndown chart. The board id is taken from the YAML file. The card is identified as the first card named "burndown chart" (case insensitive match) in the first "Done" column. If upload fails there should be an error message.

**Comment by alexandergraul** [comment]
@Ana06 I think you can close this, isn't this covered by https://github.com/openSUSE/trollolo/pull/105?

**Comment by Ana06** [comment]
@alexandergraul I think you are right. The only different is that the burndown chart is uploaded to the first card, and not to the first card called `burndown chart`. Is this enought for you @cornelius? I think it should be visible so the first card is the best place. I am going to close this, feel free to reopen it if there is something missing.
